package panificadora.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import panificadora.model.salvarDadosF;
import panificadora.model.salvarDadosP;

/**
 *
 * @author Guilherme-Pc
 */
public class TelaCadastro3 extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro3
     */
    public TelaCadastro3() {
        initComponents();
                        Date da = new Date();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd / MM / YYYY"); 
        Data.setText(formato.format(da));
        
        Timer t = new Timer(1000,new TelaCadastro3.horas());
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L1 = new javax.swing.JLabel();
        a = new javax.swing.JPanel();
        Hora = new javax.swing.JLabel();
        a1 = new javax.swing.JPanel();
        Data = new javax.swing.JLabel();
        SenhaFP = new javax.swing.JPasswordField();
        LU = new javax.swing.JLabel();
        UserFP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Ls = new javax.swing.JLabel();
        CodigoP = new javax.swing.JTextField();
        Ls1 = new javax.swing.JLabel();
        NomeP = new javax.swing.JTextField();
        Ls3 = new javax.swing.JLabel();
        DataVP = new javax.swing.JFormattedTextField();
        pesquisar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        Cadastrar = new javax.swing.JButton();
        Ls4 = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        limpar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Ls7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setResizable(false);
        getContentPane().setLayout(null);

        L1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        L1.setText("Cadastro de Produtos");
        getContentPane().add(L1);
        L1.setBounds(210, 0, 260, 29);

        a.setBackground(new java.awt.Color(0, 0, 0));
        a.setForeground(new java.awt.Color(204, 0, 0));

        Hora.setForeground(new java.awt.Color(255, 0, 0));
        a.add(Hora);

        getContentPane().add(a);
        a.setBounds(560, 30, 80, 30);

        a1.setBackground(new java.awt.Color(0, 0, 0));

        Data.setForeground(new java.awt.Color(255, 0, 0));
        a1.add(Data);

        getContentPane().add(a1);
        a1.setBounds(450, 30, 100, 30);

        SenhaFP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(SenhaFP);
        SenhaFP.setBounds(360, 110, 168, 30);

        LU.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        LU.setForeground(new java.awt.Color(255, 255, 153));
        LU.setText(" Usuário do Funcionário/ Fornecedor:");
        getContentPane().add(LU);
        LU.setBounds(100, 70, 260, 30);

        UserFP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(UserFP);
        UserFP.setBounds(360, 70, 168, 30);

        jButton1.setText("<- Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 0, 80, 29);

        Ls.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Ls.setForeground(new java.awt.Color(255, 255, 153));
        Ls.setText("Senha do Funcionário/ Fornecedor:");
        getContentPane().add(Ls);
        Ls.setBounds(110, 110, 250, 30);

        CodigoP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(CodigoP);
        CodigoP.setBounds(360, 150, 170, 30);

        Ls1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Ls1.setForeground(new java.awt.Color(255, 255, 153));
        Ls1.setText("Código de barra do produto:");
        getContentPane().add(Ls1);
        Ls1.setBounds(130, 150, 199, 30);

        NomeP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(NomeP);
        NomeP.setBounds(360, 200, 170, 30);

        Ls3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Ls3.setForeground(new java.awt.Color(255, 255, 153));
        Ls3.setText("Preço");
        getContentPane().add(Ls3);
        Ls3.setBounds(210, 280, 60, 30);

        try {
            DataVP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(DataVP);
        DataVP.setBounds(360, 240, 70, 30);

        pesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisar);
        pesquisar.setBounds(420, 370, 110, 30);

        alterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar);
        alterar.setBounds(250, 420, 110, 30);

        excluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(90, 370, 90, 30);

        Atualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Atualizar);
        Atualizar.setBounds(420, 420, 110, 30);

        Cadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar);
        Cadastrar.setBounds(250, 370, 110, 30);

        Ls4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Ls4.setForeground(new java.awt.Color(255, 255, 153));
        Ls4.setText("Nome do produto:");
        getContentPane().add(Ls4);
        Ls4.setBounds(180, 200, 129, 30);
        getContentPane().add(preco);
        preco.setBounds(320, 280, 180, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(90, 280, 270, 30);

        limpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        getContentPane().add(limpar);
        limpar.setBounds(90, 420, 90, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/fundoAmarelo.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(-30, 0, 790, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(90, 150, 270, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(90, 200, 270, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(90, 70, 270, 30);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(90, 110, 270, 30);

        Ls7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Ls7.setForeground(new java.awt.Color(255, 255, 153));
        Ls7.setText("Data de validade:");
        getContentPane().add(Ls7);
        Ls7.setBounds(180, 240, 118, 30);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/barraLaranja.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(90, 240, 270, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panificadora/imagens/fundoCadastroFornecedor.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-70, -90, 790, 630);

        setSize(new java.awt.Dimension(666, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        if(evt.getSource() == pesquisar){
            try{
                String codigo = JOptionPane.showInputDialog("Digite o Código:");

                BufferedReader ler = new BufferedReader(new FileReader("../Panificadora/Produtos/Produto"+codigo+".txt"));

                preco.setText(ler.readLine());
                NomeP.setText(ler.readLine());
                CodigoP.setText(ler.readLine());
                UserFP.setText(ler.readLine());
                SenhaFP.setText(ler.readLine());
                DataVP.setText(ler.readLine());


                ler.close();

            }catch(Exception erro){
                JOptionPane.showMessageDialog(null, "Erro: "+erro.getMessage());
            }
            UserFP.setEnabled(false);
            SenhaFP.setEnabled(false);
            CodigoP.setEnabled(false);
            NomeP.setEnabled(false);
            DataVP.setEnabled(false);
            preco.setEnabled(false);

        }
    }//GEN-LAST:event_pesquisarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
            UserFP.setEnabled(true);
            SenhaFP.setEnabled(true);
            CodigoP.setEnabled(false);
            NomeP.setEnabled(true);
            DataVP.setEnabled(true);
    }//GEN-LAST:event_alterarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        salvarDadosP ne = new salvarDadosP();
        String codigos = JOptionPane.showInputDialog("Digite o Código: ");
        
        if(NomeP.getText().equals("") || DataVP.getText().equals("") || CodigoP.getText().equals("") || UserFP.getText().equals("") || preco.getText().equals("") || (SenhaFP.getPassword().equals(""))){
                    JOptionPane.showMessageDialog(null,"Alguns campos não foram preenchidos","Aviso",JOptionPane.ERROR_MESSAGE);
        
        }else{
          //Salvar as informações do usuário
             JOptionPane.showMessageDialog(null, ne.Excluir(codigos));
        }
        
       
    }//GEN-LAST:event_excluirActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
         salvarDadosP sd = new salvarDadosP();
        sd.setUserDFD(UserFP.getText());
        sd.setSenhaDFD(String.valueOf(SenhaFP.getPassword()));
        sd.setCodigoPD(CodigoP.getText());
        sd.setNomePD(NomeP.getText());
        sd.setDataVD(DataVP.getText());
        
        if(NomeP.getText().equals("") || DataVP.getText().equals("") || CodigoP.getText().equals("") || UserFP.getText().equals("") || preco.getText().equals("") || (SenhaFP.getPassword().equals(""))){
                    JOptionPane.showMessageDialog(null,"Alguns campos não foram preenchidos","Aviso",JOptionPane.ERROR_MESSAGE);
        
        }else{
          //Salvar as informações do usuário
            JOptionPane.showMessageDialog(null, sd.Atualizar());
        }

        CodigoP.setEnabled(true);
        UserFP.setText("");
        SenhaFP.setText("");
        CodigoP.setText("");
        NomeP.setText("");
        DataVP.setText("");
    }//GEN-LAST:event_AtualizarActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        salvarDadosP sd = new salvarDadosP();

        sd.setNomePD(NomeP.getText());
        sd.setDataVD(DataVP.getText());
        sd.setCodigoPD(CodigoP.getText());
        sd.setUserDFD(UserFP.getText());
        sd.setPreco(preco.getText());
        sd.setSenhaDFD(String.valueOf(SenhaFP.getPassword()));
  
        if(NomeP.getText().equals("") || DataVP.getText().equals("") || CodigoP.getText().equals("") || UserFP.getText().equals("") || preco.getText().equals("") || (SenhaFP.getPassword().equals(""))){
                    JOptionPane.showMessageDialog(null,"Alguns campos não foram preenchidos","Aviso",JOptionPane.ERROR_MESSAGE);
        
        }else{
          //Salvar as informações do usuário
            JOptionPane.showMessageDialog(null, sd.SalvaDados());
        }

        

        CodigoP.setEnabled(true);
        UserFP.setText("");
        SenhaFP.setText("");
        CodigoP.setText("");
        NomeP.setText("");
        DataVP.setText("");
    }//GEN-LAST:event_CadastrarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        UserFP.setText("");
        SenhaFP.setText("");
        CodigoP.setText("");
        NomeP.setText("");
        DataVP.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaLogin a = new TelaLogin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JTextField CodigoP;
    private javax.swing.JLabel Data;
    private javax.swing.JFormattedTextField DataVP;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel LU;
    private javax.swing.JLabel Ls;
    private javax.swing.JLabel Ls1;
    private javax.swing.JLabel Ls3;
    private javax.swing.JLabel Ls4;
    private javax.swing.JLabel Ls7;
    private javax.swing.JTextField NomeP;
    private javax.swing.JPasswordField SenhaFP;
    private javax.swing.JTextField UserFP;
    private javax.swing.JPanel a;
    private javax.swing.JPanel a1;
    private javax.swing.JButton alterar;
    private javax.swing.JButton excluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton limpar;
    private javax.swing.JButton pesquisar;
    private javax.swing.JTextField preco;
    // End of variables declaration//GEN-END:variables

    public class horas implements ActionListener{
    @Override
    public void actionPerformed (ActionEvent e){
        Calendar c = Calendar.getInstance();
        Hora.setText(String.format("%1$tH:%1$tM:%1$tS", c));
    }
    }}
